# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LAVESHMUSIC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LAVESHMUSIC

  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'DMSwipeCards'
  pod 'SSProgressBar'
  pod 'JHSpinner'
  pod 'SDWebImage', '~> 4.0'

  target 'LAVESHMUSICTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LAVESHMUSICUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
